/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 10:15:53 GMT 2023
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.text.translate.EntityArrays;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EntityArrays_ESTest extends EntityArrays_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:APOS_ESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE()[[Ljava/lang/String;: Line 377
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.APOS_ESCAPE();
      assertEquals(1, stringArray0.length);
  }

  //Test case number: 1
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:BASIC_ESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE()[[Ljava/lang/String;: Line 358
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.BASIC_ESCAPE();
      assertEquals(4, stringArray0.length);
  }

  //Test case number: 2
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;: Line 408
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.JAVA_CTRL_CHARS_UNESCAPE();
      assertEquals(5, stringArray0.length);
  }

  //Test case number: 3
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:BASIC_UNESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE()[[Ljava/lang/String;: Line 370
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.BASIC_UNESCAPE();
      assertEquals(4, stringArray0.length);
  }

  //Test case number: 4
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;: Line 395
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.JAVA_CTRL_CHARS_ESCAPE();
      assertEquals(5, stringArray0.length);
  }

  //Test case number: 5
  /*
   * 38 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - false
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - false in context: org.apache.commons.lang3.text.translate.EntityArrays:invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 3. invert([[Ljava/lang/String;)[[Ljava/lang/String;_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 417
   * Goal 5. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 418
   * Goal 6. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 419
   * Goal 7. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 420
   * Goal 8. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 9. Weak Mutation 0: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 0
   * Goal 10. Weak Mutation 1: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 1
   * Goal 11. Weak Mutation 2: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> -1
   * Goal 12. Weak Mutation 3: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 3
   * Goal 13. Weak Mutation 4: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceConstant - 0 -> 1
   * Goal 14. Weak Mutation 5: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp Negation of i
   * Goal 15. Weak Mutation 6: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp IINC 1 i
   * Goal 16. Weak Mutation 7: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp IINC -1 i
   * Goal 17. Weak Mutation 8: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceVariable array -> newarray
   * Goal 18. Weak Mutation 9: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceComparisonOperator >= -> -1
   * Goal 19. Weak Mutation 12: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceVariable newarray -> array
   * Goal 20. Weak Mutation 13: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp Negation of i
   * Goal 21. Weak Mutation 14: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC 1 i
   * Goal 22. Weak Mutation 15: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC -1 i
   * Goal 23. Weak Mutation 16: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceConstant - 0 -> 1
   * Goal 24. Weak Mutation 17: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceVariable array -> newarray
   * Goal 25. Weak Mutation 18: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp Negation of i
   * Goal 26. Weak Mutation 19: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC 1 i
   * Goal 27. Weak Mutation 20: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC -1 i
   * Goal 28. Weak Mutation 21: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceConstant - 1 -> 0
   * Goal 29. Weak Mutation 22: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceVariable newarray -> array
   * Goal 30. Weak Mutation 23: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp Negation of i
   * Goal 31. Weak Mutation 24: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC 1 i
   * Goal 32. Weak Mutation 25: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC -1 i
   * Goal 33. Weak Mutation 26: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceConstant - 1 -> 0
   * Goal 34. Weak Mutation 27: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceVariable array -> newarray
   * Goal 35. Weak Mutation 28: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp Negation of i
   * Goal 36. Weak Mutation 29: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC 1 i
   * Goal 37. Weak Mutation 30: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC -1 i
   * Goal 38. Weak Mutation 31: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[][] stringArray0 = new String[3][2];
      String[] stringArray1 = new String[1];
      stringArray0[1] = stringArray1;
      // Undeclared exception!
      try { 
        EntityArrays.invert(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.apache.commons.lang3.text.translate.EntityArrays", e);
      }
  }

  //Test case number: 6
  /*
   * 19 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - true
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - true in context: org.apache.commons.lang3.text.translate.EntityArrays:invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:EmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 417
   * Goal 5. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 418
   * Goal 6. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 422
   * Goal 7. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 8. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 9. Weak Mutation 0: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 0
   * Goal 10. Weak Mutation 1: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 1
   * Goal 11. Weak Mutation 2: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> -1
   * Goal 12. Weak Mutation 3: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 3
   * Goal 13. Weak Mutation 4: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceConstant - 0 -> 1
   * Goal 14. Weak Mutation 5: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp Negation of i
   * Goal 15. Weak Mutation 6: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp IINC 1 i
   * Goal 16. Weak Mutation 7: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp IINC -1 i
   * Goal 17. Weak Mutation 8: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceVariable array -> newarray
   * Goal 18. Weak Mutation 10: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceComparisonOperator >= -> >
   * Goal 19. Weak Mutation 32: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:422 - ReplaceVariable newarray -> array
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[][] stringArray0 = new String[0][2];
      String[][] stringArray1 = EntityArrays.invert(stringArray0);
      assertNotSame(stringArray1, stringArray0);
  }

  //Test case number: 7
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;: Line 349
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.HTML40_EXTENDED_UNESCAPE();
      assertEquals(151, stringArray0.length);
  }

  //Test case number: 8
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;: Line 147
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.HTML40_EXTENDED_ESCAPE();
      assertEquals(151, stringArray0.length);
  }

  //Test case number: 9
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:ISO8859_1_UNESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE()[[Ljava/lang/String;: Line 138
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.ISO8859_1_UNESCAPE();
      assertEquals(96, stringArray0.length);
  }

  //Test case number: 10
  /*
   * 3 covered goals:
   * Goal 1. invert([[Ljava/lang/String;)[[Ljava/lang/String;_java.lang.NullPointerException_IMPLICIT
   * Goal 2. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 417
   * Goal 3. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        EntityArrays.invert((String[][]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.EntityArrays", e);
      }
  }

  //Test case number: 11
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.<init>()V
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EntityArrays entityArrays0 = new EntityArrays();
  }

  //Test case number: 12
  /*
   * 6 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:APOS_UNESCAPE()[[Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE()[[Ljava/lang/String;: Line 386
   * Goal 5. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE()[[Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE()[[Ljava/lang/String;
   */

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.APOS_UNESCAPE();
      assertEquals(1, stringArray0.length);
  }

  //Test case number: 13
  /*
   * 50 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE()[[Ljava/lang/String;: root-Branch
   * Goal 2. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - true
   * Goal 3. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - false
   * Goal 4. Branch org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE()[[Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.text.translate.EntityArrays:ISO8859_1_ESCAPE()[[Ljava/lang/String;
   * Goal 5. Branch org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - true in context: org.apache.commons.lang3.text.translate.EntityArrays:invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 6. Branch org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: I15 Branch 1 IF_ICMPGE L418 - false in context: org.apache.commons.lang3.text.translate.EntityArrays:invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 7. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE()[[Ljava/lang/String;:NonEmptyArray
   * Goal 8. [Output]: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:NonEmptyArray
   * Goal 9. org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE()[[Ljava/lang/String;: Line 34
   * Goal 10. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 417
   * Goal 11. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 418
   * Goal 12. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 419
   * Goal 13. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 420
   * Goal 14. org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;: Line 422
   * Goal 15. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE()[[Ljava/lang/String;
   * Goal 16. [METHOD] org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 17. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE()[[Ljava/lang/String;
   * Goal 18. [METHODNOEX] org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;
   * Goal 19. Weak Mutation 0: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 0
   * Goal 20. Weak Mutation 1: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 1
   * Goal 21. Weak Mutation 2: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> -1
   * Goal 22. Weak Mutation 3: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:417 - ReplaceConstant - 2 -> 3
   * Goal 23. Weak Mutation 4: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceConstant - 0 -> 1
   * Goal 24. Weak Mutation 5: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp Negation of i
   * Goal 25. Weak Mutation 6: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp IINC 1 i
   * Goal 26. Weak Mutation 7: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - InsertUnaryOp IINC -1 i
   * Goal 27. Weak Mutation 8: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceVariable array -> newarray
   * Goal 28. Weak Mutation 9: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceComparisonOperator >= -> -1
   * Goal 29. Weak Mutation 10: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:418 - ReplaceComparisonOperator >= -> >
   * Goal 30. Weak Mutation 12: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceVariable newarray -> array
   * Goal 31. Weak Mutation 13: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp Negation of i
   * Goal 32. Weak Mutation 14: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC 1 i
   * Goal 33. Weak Mutation 15: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC -1 i
   * Goal 34. Weak Mutation 16: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceConstant - 0 -> 1
   * Goal 35. Weak Mutation 17: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceVariable array -> newarray
   * Goal 36. Weak Mutation 18: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp Negation of i
   * Goal 37. Weak Mutation 19: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC 1 i
   * Goal 38. Weak Mutation 20: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - InsertUnaryOp IINC -1 i
   * Goal 39. Weak Mutation 21: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:419 - ReplaceConstant - 1 -> 0
   * Goal 40. Weak Mutation 22: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceVariable newarray -> array
   * Goal 41. Weak Mutation 23: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp Negation of i
   * Goal 42. Weak Mutation 24: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC 1 i
   * Goal 43. Weak Mutation 25: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC -1 i
   * Goal 44. Weak Mutation 26: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceConstant - 1 -> 0
   * Goal 45. Weak Mutation 27: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceVariable array -> newarray
   * Goal 46. Weak Mutation 28: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp Negation of i
   * Goal 47. Weak Mutation 29: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC 1 i
   * Goal 48. Weak Mutation 30: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - InsertUnaryOp IINC -1 i
   * Goal 49. Weak Mutation 31: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:420 - ReplaceConstant - 0 -> 1
   * Goal 50. Weak Mutation 32: org.apache.commons.lang3.text.translate.EntityArrays.invert([[Ljava/lang/String;)[[Ljava/lang/String;:422 - ReplaceVariable newarray -> array
   */

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[][] stringArray0 = EntityArrays.ISO8859_1_ESCAPE();
      String[][] stringArray1 = EntityArrays.invert(stringArray0);
      assertNotSame(stringArray1, stringArray0);
  }
}
