/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 13:51:17 GMT 2023
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.FormatFlagsConversionMismatchException;
import java.util.IllegalFormatConversionException;
import java.util.IllegalFormatFlagsException;
import java.util.UnknownFormatConversionException;
import org.apache.commons.lang3.Validate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Validate_ESTest extends Validate_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. isTrue(ZLjava/lang/String;J)V_java.util.IllegalFormatFlagsException_IMPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 122
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 10: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 1 -> 0
   * Goal 12. Weak Mutation 11: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 12: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - InsertUnaryOp Negation of value
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false, "6]b%(%-", 0L);
        fail("Expecting exception: IllegalFormatFlagsException");
      
      } catch(IllegalFormatFlagsException e) {
         //
         // Flags = '('
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  //Test case number: 1
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. isTrue(ZLjava/lang/String;J)V_java.util.FormatFlagsConversionMismatchException_IMPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 122
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 10: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 1 -> 0
   * Goal 12. Weak Mutation 11: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 12: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - InsertUnaryOp Negation of value
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false, "U-`'(%(Si", 1L);
        fail("Expecting exception: FormatFlagsConversionMismatchException");
      
      } catch(FormatFlagsConversionMismatchException e) {
         //
         // Conversion = s, Flags = (
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang3.Validate.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang3.Validate.<init>()V
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Validate validate0 = new Validate();
  }

  //Test case number: 3
  /*
   * 10 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - true
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - true in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 124
   * Goal 5. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Validate.isTrue(true, "The validated character sequence is blank", 0L);
  }

  //Test case number: 4
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. isTrue(ZLjava/lang/String;J)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 122
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 10: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 1 -> 0
   * Goal 12. Weak Mutation 11: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 12: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - InsertUnaryOp Negation of value
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false, "", 55L);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // 
         //
         verifyException("org.apache.commons.lang3.Validate", e);
      }
  }

  //Test case number: 5
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. isTrue(ZLjava/lang/String;J)V_java.util.UnknownFormatConversionException_IMPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 122
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 10: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 1 -> 0
   * Goal 12. Weak Mutation 11: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 12: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - InsertUnaryOp Negation of value
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false, "PkaDnTe3no6%1mXc3", (-1L));
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = 'm'
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  //Test case number: 6
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. isTrue(ZLjava/lang/String;J)V_java.lang.NullPointerException_IMPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 122
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 10: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 1 -> 0
   * Goal 12. Weak Mutation 11: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 12: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - InsertUnaryOp Negation of value
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false, (String) null, 6083L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 7
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: I3 Branch 2 IFNE L121 - false in context: org.apache.commons.lang3.Validate:isTrue(ZLjava/lang/String;J)V
   * Goal 3. isTrue(ZLjava/lang/String;J)V_java.util.IllegalFormatConversionException_IMPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 121
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V: Line 122
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V
   * Goal 7. Weak Mutation 6: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 7: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 8: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 9: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:121 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 10: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 1 -> 0
   * Goal 12. Weak Mutation 11: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 12: org.apache.commons.lang3.Validate.isTrue(ZLjava/lang/String;J)V:122 - InsertUnaryOp Negation of value
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false, "4%f4P2sP}pmqlY", 3555L);
        fail("Expecting exception: IllegalFormatConversionException");
      
      } catch(IllegalFormatConversionException e) {
         //
         // f != java.lang.Long
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }
}
