/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 17:43:52 GMT 2023
 */

package org.apache.commons.lang.time;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang.time.StopWatch;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StopWatch_ESTest extends StopWatch_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 67 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - true
   * Goal 5. org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - false
   * Goal 6. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - true in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - false in context: org.apache.commons.lang.time.StopWatch:suspend()V
   * Goal 11. suspend()V_java.lang.IllegalStateException_EXPLICIT
   * Goal 12. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 18. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 19. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 20. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 21. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 22. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 23. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 24. org.apache.commons.lang.time.StopWatch.stop()V: Line 115
   * Goal 25. org.apache.commons.lang.time.StopWatch.stop()V: Line 118
   * Goal 26. org.apache.commons.lang.time.StopWatch.stop()V: Line 119
   * Goal 27. org.apache.commons.lang.time.StopWatch.stop()V: Line 120
   * Goal 28. org.apache.commons.lang.time.StopWatch.suspend()V: Line 176
   * Goal 29. org.apache.commons.lang.time.StopWatch.suspend()V: Line 177
   * Goal 30. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 31. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 32. [METHOD] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 33. [METHOD] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 34. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 35. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 36. [METHODNOEX] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 37. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 39. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 40. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 41. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 42. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 43. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 44. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 45. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 46. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 47. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 48. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 49. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 50. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 51. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 52. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 53. Weak Mutation 22: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 54. Weak Mutation 23: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 55. Weak Mutation 24: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 56. Weak Mutation 25: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 1 -> 0
   * Goal 57. Weak Mutation 26: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> !=
   * Goal 58. Weak Mutation 39: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 0
   * Goal 59. Weak Mutation 40: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 1
   * Goal 60. Weak Mutation 41: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> -1
   * Goal 61. Weak Mutation 42: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 3
   * Goal 62. Weak Mutation 86: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp Negation
   * Goal 63. Weak Mutation 87: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp +1
   * Goal 64. Weak Mutation 88: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp -1
   * Goal 65. Weak Mutation 89: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceConstant - 1 -> 0
   * Goal 66. Weak Mutation 90: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceComparisonOperator == -> !=
   * Goal 67. Weak Mutation 91: org.apache.commons.lang.time.StopWatch.suspend()V:177 - ReplaceConstant - Stopwatch must be running to suspend.  -> 
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      stopWatch0.stop();
      // Undeclared exception!
      try { 
        stopWatch0.suspend();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stopwatch must be running to suspend. 
         //
         verifyException("org.apache.commons.lang.time.StopWatch", e);
      }
  }

  //Test case number: 1
  /*
   * 84 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - false
   * Goal 5. org.apache.commons.lang.time.StopWatch.stop()V: I9 Branch 4 IF_ICMPEQ L115 - true
   * Goal 6. org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - true
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.stop()V: I9 Branch 4 IF_ICMPEQ L115 - true in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 11. Branch org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - false in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 12. Branch org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - true in context: org.apache.commons.lang.time.StopWatch:suspend()V
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 18. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 19. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 20. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 21. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 22. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 23. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 24. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 25. org.apache.commons.lang.time.StopWatch.stop()V: Line 115
   * Goal 26. org.apache.commons.lang.time.StopWatch.stop()V: Line 118
   * Goal 27. org.apache.commons.lang.time.StopWatch.stop()V: Line 119
   * Goal 28. org.apache.commons.lang.time.StopWatch.stop()V: Line 120
   * Goal 29. org.apache.commons.lang.time.StopWatch.suspend()V: Line 176
   * Goal 30. org.apache.commons.lang.time.StopWatch.suspend()V: Line 179
   * Goal 31. org.apache.commons.lang.time.StopWatch.suspend()V: Line 180
   * Goal 32. org.apache.commons.lang.time.StopWatch.suspend()V: Line 181
   * Goal 33. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 34. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 35. [METHOD] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 36. [METHOD] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 37. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 38. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 39. [METHODNOEX] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 40. [METHODNOEX] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 41. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 42. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 43. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 44. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 45. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 46. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 47. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 48. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 49. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 50. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 51. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 52. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 53. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 54. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 55. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 56. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 57. Weak Mutation 22: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 58. Weak Mutation 23: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 59. Weak Mutation 24: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 60. Weak Mutation 25: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 1 -> 0
   * Goal 61. Weak Mutation 26: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> !=
   * Goal 62. Weak Mutation 27: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 63. Weak Mutation 28: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 64. Weak Mutation 29: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 65. Weak Mutation 30: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 0
   * Goal 66. Weak Mutation 31: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 1
   * Goal 67. Weak Mutation 32: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> -1
   * Goal 68. Weak Mutation 33: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 2
   * Goal 69. Weak Mutation 34: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 4
   * Goal 70. Weak Mutation 35: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> -2
   * Goal 71. Weak Mutation 39: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 0
   * Goal 72. Weak Mutation 40: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 1
   * Goal 73. Weak Mutation 41: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> -1
   * Goal 74. Weak Mutation 42: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 3
   * Goal 75. Weak Mutation 86: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp Negation
   * Goal 76. Weak Mutation 87: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp +1
   * Goal 77. Weak Mutation 88: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp -1
   * Goal 78. Weak Mutation 89: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceConstant - 1 -> 0
   * Goal 79. Weak Mutation 90: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceComparisonOperator == -> !=
   * Goal 80. Weak Mutation 92: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 0
   * Goal 81. Weak Mutation 93: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 1
   * Goal 82. Weak Mutation 94: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> -1
   * Goal 83. Weak Mutation 95: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 2
   * Goal 84. Weak Mutation 96: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 4
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      stopWatch0.suspend();
      stopWatch0.stop();
  }

  //Test case number: 2
  /*
   * 83 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false
   * Goal 5. org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - true
   * Goal 6. org.apache.commons.lang.time.StopWatch.getTime()J: I22 Branch 11 IFNE L212 - true
   * Goal 7. org.apache.commons.lang.time.StopWatch.getTime()J: I32 Branch 12 IF_ICMPNE L215 - false
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 11. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 12. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - true in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 13. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I22 Branch 11 IFNE L212 - true in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 14. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I32 Branch 12 IF_ICMPNE L215 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 15. [Output]: org.apache.commons.lang.time.StopWatch.getTime()J:Zero
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 18. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 19. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 20. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 21. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 22. org.apache.commons.lang.time.StopWatch.getTime()J: Line 209
   * Goal 23. org.apache.commons.lang.time.StopWatch.getTime()J: Line 212
   * Goal 24. org.apache.commons.lang.time.StopWatch.getTime()J: Line 215
   * Goal 25. org.apache.commons.lang.time.StopWatch.getTime()J: Line 216
   * Goal 26. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 27. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 28. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 29. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 30. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 31. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 32. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 33. [METHOD] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 34. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 35. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 36. [METHODNOEX] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 37. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 38. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 39. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 40. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 41. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 42. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 43. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 44. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 45. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 46. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 47. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 48. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 49. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 50. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 51. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 52. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 53. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 54. Weak Mutation 123: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 124: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 56. Weak Mutation 125: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 57. Weak Mutation 126: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 0
   * Goal 58. Weak Mutation 127: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 1
   * Goal 59. Weak Mutation 128: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> -1
   * Goal 60. Weak Mutation 129: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 3
   * Goal 61. Weak Mutation 132: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator == -> <=
   * Goal 62. Weak Mutation 133: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 63. Weak Mutation 134: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 64. Weak Mutation 135: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 65. Weak Mutation 136: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 0
   * Goal 66. Weak Mutation 137: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 1
   * Goal 67. Weak Mutation 138: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> -1
   * Goal 68. Weak Mutation 139: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 2
   * Goal 69. Weak Mutation 140: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 4
   * Goal 70. Weak Mutation 143: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator != -> >
   * Goal 71. Weak Mutation 150: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp Negation
   * Goal 72. Weak Mutation 151: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp +1
   * Goal 73. Weak Mutation 152: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp -1
   * Goal 74. Weak Mutation 154: org.apache.commons.lang.time.StopWatch.getTime()J:212 - ReplaceComparisonOperator != -> <
   * Goal 75. Weak Mutation 158: org.apache.commons.lang.time.StopWatch.getTime()J:215 - InsertUnaryOp Negation
   * Goal 76. Weak Mutation 159: org.apache.commons.lang.time.StopWatch.getTime()J:215 - InsertUnaryOp +1
   * Goal 77. Weak Mutation 160: org.apache.commons.lang.time.StopWatch.getTime()J:215 - InsertUnaryOp -1
   * Goal 78. Weak Mutation 161: org.apache.commons.lang.time.StopWatch.getTime()J:215 - ReplaceConstant - 1 -> 0
   * Goal 79. Weak Mutation 162: org.apache.commons.lang.time.StopWatch.getTime()J:215 - ReplaceComparisonOperator != -> ==
   * Goal 80. Weak Mutation 163: org.apache.commons.lang.time.StopWatch.getTime()J:216 - InsertUnaryOp Negation
   * Goal 81. Weak Mutation 164: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> +
   * Goal 82. Weak Mutation 166: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> *
   * Goal 83. Weak Mutation 167: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      long long0 = stopWatch0.getTime();
      assertEquals(0L, long0);
  }

  //Test case number: 3
  /*
   * 61 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - false
   * Goal 4. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 5. org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - true
   * Goal 6. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - false in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - true in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 11. start()V_java.lang.IllegalStateException_EXPLICIT
   * Goal 12. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 18. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 19. org.apache.commons.lang.time.StopWatch.start()V: Line 97
   * Goal 20. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 21. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 22. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 23. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 24. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 25. org.apache.commons.lang.time.StopWatch.stop()V: Line 115
   * Goal 26. org.apache.commons.lang.time.StopWatch.stop()V: Line 118
   * Goal 27. org.apache.commons.lang.time.StopWatch.stop()V: Line 119
   * Goal 28. org.apache.commons.lang.time.StopWatch.stop()V: Line 120
   * Goal 29. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 30. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 31. [METHOD] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 32. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 33. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 34. [METHODNOEX] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 35. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 36. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 37. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 38. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 39. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 40. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 41. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 42. Weak Mutation 7: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> -1
   * Goal 43. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 44. Weak Mutation 10: org.apache.commons.lang.time.StopWatch.start()V:97 - ReplaceConstant - Stopwatch must be reset before being restarted.  -> 
   * Goal 45. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 46. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 47. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 48. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 49. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 50. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 51. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 52. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 53. Weak Mutation 22: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 54. Weak Mutation 23: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 55. Weak Mutation 24: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 56. Weak Mutation 25: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 1 -> 0
   * Goal 57. Weak Mutation 26: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> !=
   * Goal 58. Weak Mutation 39: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 0
   * Goal 59. Weak Mutation 40: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 1
   * Goal 60. Weak Mutation 41: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> -1
   * Goal 61. Weak Mutation 42: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 3
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      stopWatch0.stop();
      // Undeclared exception!
      try { 
        stopWatch0.start();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stopwatch must be reset before being restarted. 
         //
         verifyException("org.apache.commons.lang.time.StopWatch", e);
      }
  }

  //Test case number: 4
  /*
   * 84 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false
   * Goal 5. org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - true
   * Goal 6. org.apache.commons.lang.time.StopWatch.getTime()J: I22 Branch 11 IFNE L212 - true
   * Goal 7. org.apache.commons.lang.time.StopWatch.getTime()J: I32 Branch 12 IF_ICMPNE L215 - false
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 11. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 12. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - true in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 13. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I22 Branch 11 IFNE L212 - true in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 14. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I32 Branch 12 IF_ICMPNE L215 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 15. [Output]: org.apache.commons.lang.time.StopWatch.getTime()J:Positive
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 18. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 19. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 20. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 21. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 22. org.apache.commons.lang.time.StopWatch.getTime()J: Line 209
   * Goal 23. org.apache.commons.lang.time.StopWatch.getTime()J: Line 212
   * Goal 24. org.apache.commons.lang.time.StopWatch.getTime()J: Line 215
   * Goal 25. org.apache.commons.lang.time.StopWatch.getTime()J: Line 216
   * Goal 26. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 27. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 28. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 29. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 30. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 31. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 32. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 33. [METHOD] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 34. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 35. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 36. [METHODNOEX] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 37. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 38. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 39. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 40. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 41. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 42. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 43. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 44. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 45. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 46. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 47. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 48. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 49. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 50. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 51. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 52. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 53. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 54. Weak Mutation 123: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 124: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 56. Weak Mutation 125: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 57. Weak Mutation 126: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 0
   * Goal 58. Weak Mutation 127: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 1
   * Goal 59. Weak Mutation 128: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> -1
   * Goal 60. Weak Mutation 129: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 3
   * Goal 61. Weak Mutation 132: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator == -> <=
   * Goal 62. Weak Mutation 133: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 63. Weak Mutation 134: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 64. Weak Mutation 135: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 65. Weak Mutation 136: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 0
   * Goal 66. Weak Mutation 137: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 1
   * Goal 67. Weak Mutation 138: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> -1
   * Goal 68. Weak Mutation 139: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 2
   * Goal 69. Weak Mutation 140: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 4
   * Goal 70. Weak Mutation 143: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator != -> >
   * Goal 71. Weak Mutation 150: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp Negation
   * Goal 72. Weak Mutation 151: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp +1
   * Goal 73. Weak Mutation 152: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp -1
   * Goal 74. Weak Mutation 154: org.apache.commons.lang.time.StopWatch.getTime()J:212 - ReplaceComparisonOperator != -> <
   * Goal 75. Weak Mutation 158: org.apache.commons.lang.time.StopWatch.getTime()J:215 - InsertUnaryOp Negation
   * Goal 76. Weak Mutation 159: org.apache.commons.lang.time.StopWatch.getTime()J:215 - InsertUnaryOp +1
   * Goal 77. Weak Mutation 160: org.apache.commons.lang.time.StopWatch.getTime()J:215 - InsertUnaryOp -1
   * Goal 78. Weak Mutation 161: org.apache.commons.lang.time.StopWatch.getTime()J:215 - ReplaceConstant - 1 -> 0
   * Goal 79. Weak Mutation 162: org.apache.commons.lang.time.StopWatch.getTime()J:215 - ReplaceComparisonOperator != -> ==
   * Goal 80. Weak Mutation 163: org.apache.commons.lang.time.StopWatch.getTime()J:216 - InsertUnaryOp Negation
   * Goal 81. Weak Mutation 164: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> +
   * Goal 82. Weak Mutation 165: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> %
   * Goal 83. Weak Mutation 166: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> *
   * Goal 84. Weak Mutation 167: org.apache.commons.lang.time.StopWatch.getTime()J:216 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      System.setCurrentTimeMillis((-1L));
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      System.setCurrentTimeMillis(1640L);
      long long0 = stopWatch0.getTime();
      assertEquals(1641L, long0);
  }

  //Test case number: 5
  /*
   * 87 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - true
   * Goal 5. org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false
   * Goal 6. org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - false
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - true in context: org.apache.commons.lang.time.StopWatch:suspend()V
   * Goal 11. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 12. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 13. [Output]: org.apache.commons.lang.time.StopWatch.getTime()J:Zero
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 18. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 19. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 20. org.apache.commons.lang.time.StopWatch.getTime()J: Line 209
   * Goal 21. org.apache.commons.lang.time.StopWatch.getTime()J: Line 210
   * Goal 22. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 23. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 24. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 25. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 26. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 27. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 28. org.apache.commons.lang.time.StopWatch.suspend()V: Line 176
   * Goal 29. org.apache.commons.lang.time.StopWatch.suspend()V: Line 179
   * Goal 30. org.apache.commons.lang.time.StopWatch.suspend()V: Line 180
   * Goal 31. org.apache.commons.lang.time.StopWatch.suspend()V: Line 181
   * Goal 32. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 33. [METHOD] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 34. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 35. [METHOD] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 36. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 37. [METHODNOEX] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 38. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 39. [METHODNOEX] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 40. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 42. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 43. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 44. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 45. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 46. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 47. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 48. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 49. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 50. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 51. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 52. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 53. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 54. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 55. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 56. Weak Mutation 86: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp Negation
   * Goal 57. Weak Mutation 87: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp +1
   * Goal 58. Weak Mutation 88: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp -1
   * Goal 59. Weak Mutation 89: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceConstant - 1 -> 0
   * Goal 60. Weak Mutation 90: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceComparisonOperator == -> !=
   * Goal 61. Weak Mutation 92: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 0
   * Goal 62. Weak Mutation 93: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 1
   * Goal 63. Weak Mutation 94: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> -1
   * Goal 64. Weak Mutation 95: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 2
   * Goal 65. Weak Mutation 96: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 4
   * Goal 66. Weak Mutation 123: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 67. Weak Mutation 124: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 68. Weak Mutation 125: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 69. Weak Mutation 126: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 0
   * Goal 70. Weak Mutation 127: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 1
   * Goal 71. Weak Mutation 128: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> -1
   * Goal 72. Weak Mutation 129: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 3
   * Goal 73. Weak Mutation 131: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator == -> >=
   * Goal 74. Weak Mutation 133: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 75. Weak Mutation 134: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 76. Weak Mutation 135: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 77. Weak Mutation 136: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 0
   * Goal 78. Weak Mutation 137: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 1
   * Goal 79. Weak Mutation 138: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> -1
   * Goal 80. Weak Mutation 139: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 2
   * Goal 81. Weak Mutation 140: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 4
   * Goal 82. Weak Mutation 141: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator != -> -1
   * Goal 83. Weak Mutation 144: org.apache.commons.lang.time.StopWatch.getTime()J:210 - InsertUnaryOp Negation
   * Goal 84. Weak Mutation 145: org.apache.commons.lang.time.StopWatch.getTime()J:210 - InsertUnaryOp Negation
   * Goal 85. Weak Mutation 146: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> +
   * Goal 86. Weak Mutation 148: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> *
   * Goal 87. Weak Mutation 149: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      stopWatch0.suspend();
      long long0 = stopWatch0.getTime();
      assertEquals(0L, long0);
  }

  //Test case number: 6
  /*
   * 33 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - false
   * Goal 3. org.apache.commons.lang.time.StopWatch.stop()V: I9 Branch 4 IF_ICMPEQ L115 - false
   * Goal 4. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 5. Branch org.apache.commons.lang.time.StopWatch.stop()V: I9 Branch 4 IF_ICMPEQ L115 - false in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 6. Branch org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - false in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 7. stop()V_java.lang.IllegalStateException_EXPLICIT
   * Goal 8. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 9. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 10. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 11. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 12. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 14. org.apache.commons.lang.time.StopWatch.stop()V: Line 115
   * Goal 15. org.apache.commons.lang.time.StopWatch.stop()V: Line 116
   * Goal 16. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 17. [METHOD] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 18. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 19. Weak Mutation 22: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 20. Weak Mutation 23: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 21. Weak Mutation 24: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 22. Weak Mutation 25: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 1 -> 0
   * Goal 23. Weak Mutation 26: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> !=
   * Goal 24. Weak Mutation 27: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 28: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 26. Weak Mutation 29: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 27. Weak Mutation 30: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 0
   * Goal 28. Weak Mutation 31: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 1
   * Goal 29. Weak Mutation 32: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> -1
   * Goal 30. Weak Mutation 33: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 2
   * Goal 31. Weak Mutation 34: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 3 -> 4
   * Goal 32. Weak Mutation 37: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> <=
   * Goal 33. Weak Mutation 38: org.apache.commons.lang.time.StopWatch.stop()V:116 - ReplaceConstant - Stopwatch is not running.  -> 
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      // Undeclared exception!
      try { 
        stopWatch0.stop();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stopwatch is not running. 
         //
         verifyException("org.apache.commons.lang.time.StopWatch", e);
      }
  }

  //Test case number: 7
  /*
   * 63 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - false
   * Goal 5. org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - true
   * Goal 6. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - false in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.suspend()V: I5 Branch 7 IF_ICMPEQ L176 - true in context: org.apache.commons.lang.time.StopWatch:suspend()V
   * Goal 11. start()V_java.lang.IllegalStateException_EXPLICIT
   * Goal 12. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 18. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 19. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 20. org.apache.commons.lang.time.StopWatch.start()V: Line 100
   * Goal 21. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 22. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 23. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 24. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 25. org.apache.commons.lang.time.StopWatch.suspend()V: Line 176
   * Goal 26. org.apache.commons.lang.time.StopWatch.suspend()V: Line 179
   * Goal 27. org.apache.commons.lang.time.StopWatch.suspend()V: Line 180
   * Goal 28. org.apache.commons.lang.time.StopWatch.suspend()V: Line 181
   * Goal 29. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 30. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 31. [METHOD] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 32. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 33. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 34. [METHODNOEX] org.apache.commons.lang.time.StopWatch.suspend()V
   * Goal 35. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 36. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 37. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 38. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 39. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 40. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 41. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 42. Weak Mutation 8: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> <
   * Goal 43. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 44. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 45. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 46. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 47. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 48. Weak Mutation 15: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> >=
   * Goal 49. Weak Mutation 17: org.apache.commons.lang.time.StopWatch.start()V:100 - ReplaceConstant - Stopwatch already started.  -> 
   * Goal 50. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 51. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 52. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 53. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 54. Weak Mutation 86: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 87: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp +1
   * Goal 56. Weak Mutation 88: org.apache.commons.lang.time.StopWatch.suspend()V:176 - InsertUnaryOp -1
   * Goal 57. Weak Mutation 89: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceConstant - 1 -> 0
   * Goal 58. Weak Mutation 90: org.apache.commons.lang.time.StopWatch.suspend()V:176 - ReplaceComparisonOperator == -> !=
   * Goal 59. Weak Mutation 92: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 0
   * Goal 60. Weak Mutation 93: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 1
   * Goal 61. Weak Mutation 94: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> -1
   * Goal 62. Weak Mutation 95: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 2
   * Goal 63. Weak Mutation 96: org.apache.commons.lang.time.StopWatch.suspend()V:180 - ReplaceConstant - 3 -> 4
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      stopWatch0.suspend();
      // Undeclared exception!
      try { 
        stopWatch0.start();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Stopwatch already started. 
         //
         verifyException("org.apache.commons.lang.time.StopWatch", e);
      }
  }

  //Test case number: 8
  /*
   * 45 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false
   * Goal 3. org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.getTime()J: I22 Branch 11 IFNE L212 - false
   * Goal 5. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 6. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I9 Branch 10 IF_ICMPNE L209 - true in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I22 Branch 11 IFNE L212 - false in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 9. [Output]: org.apache.commons.lang.time.StopWatch.getTime()J:Zero
   * Goal 10. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 11. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 12. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 16. org.apache.commons.lang.time.StopWatch.getTime()J: Line 209
   * Goal 17. org.apache.commons.lang.time.StopWatch.getTime()J: Line 212
   * Goal 18. org.apache.commons.lang.time.StopWatch.getTime()J: Line 213
   * Goal 19. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 20. [METHOD] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 21. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 22. [METHODNOEX] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 23. Weak Mutation 123: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 24. Weak Mutation 124: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 25. Weak Mutation 125: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 26. Weak Mutation 126: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 0
   * Goal 27. Weak Mutation 127: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 1
   * Goal 28. Weak Mutation 128: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> -1
   * Goal 29. Weak Mutation 129: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 3
   * Goal 30. Weak Mutation 132: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator == -> <=
   * Goal 31. Weak Mutation 133: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 32. Weak Mutation 134: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 33. Weak Mutation 135: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 34. Weak Mutation 136: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 0
   * Goal 35. Weak Mutation 137: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 1
   * Goal 36. Weak Mutation 138: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> -1
   * Goal 37. Weak Mutation 139: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 2
   * Goal 38. Weak Mutation 140: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 3 -> 4
   * Goal 39. Weak Mutation 143: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator != -> >
   * Goal 40. Weak Mutation 150: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp Negation
   * Goal 41. Weak Mutation 151: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp +1
   * Goal 42. Weak Mutation 152: org.apache.commons.lang.time.StopWatch.getTime()J:212 - InsertUnaryOp -1
   * Goal 43. Weak Mutation 153: org.apache.commons.lang.time.StopWatch.getTime()J:212 - ReplaceComparisonOperator != -> -1
   * Goal 44. Weak Mutation 156: org.apache.commons.lang.time.StopWatch.getTime()J:213 - ReplaceConstant - 0 -> 1
   * Goal 45. Weak Mutation 157: org.apache.commons.lang.time.StopWatch.getTime()J:213 - ReplaceConstant - 0 -> -1
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      long long0 = stopWatch0.getTime();
      assertEquals(0L, long0);
  }

  //Test case number: 9
  /*
   * 76 covered goals:
   * Goal 1. org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch
   * Goal 2. org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true
   * Goal 3. org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true
   * Goal 4. org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - true
   * Goal 5. org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - true
   * Goal 6. Branch org.apache.commons.lang.time.StopWatch.<init>()V: root-Branch in context: org.apache.commons.lang.time.StopWatch:<init>()V
   * Goal 7. Branch org.apache.commons.lang.time.StopWatch.start()V: I5 Branch 1 IF_ICMPNE L96 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 8. Branch org.apache.commons.lang.time.StopWatch.start()V: I30 Branch 2 IFEQ L99 - true in context: org.apache.commons.lang.time.StopWatch:start()V
   * Goal 9. Branch org.apache.commons.lang.time.StopWatch.stop()V: I5 Branch 3 IF_ICMPEQ L115 - true in context: org.apache.commons.lang.time.StopWatch:stop()V
   * Goal 10. Branch org.apache.commons.lang.time.StopWatch.getTime()J: I5 Branch 9 IF_ICMPEQ L209 - true in context: org.apache.commons.lang.time.StopWatch:getTime()J
   * Goal 11. [Output]: org.apache.commons.lang.time.StopWatch.getTime()J:Negative
   * Goal 12. org.apache.commons.lang.time.StopWatch.<init>()V: Line 65
   * Goal 13. org.apache.commons.lang.time.StopWatch.<init>()V: Line 70
   * Goal 14. org.apache.commons.lang.time.StopWatch.<init>()V: Line 75
   * Goal 15. org.apache.commons.lang.time.StopWatch.<init>()V: Line 79
   * Goal 16. org.apache.commons.lang.time.StopWatch.<init>()V: Line 85
   * Goal 17. org.apache.commons.lang.time.StopWatch.<init>()V: Line 86
   * Goal 18. org.apache.commons.lang.time.StopWatch.getTime()J: Line 209
   * Goal 19. org.apache.commons.lang.time.StopWatch.getTime()J: Line 210
   * Goal 20. org.apache.commons.lang.time.StopWatch.start()V: Line 96
   * Goal 21. org.apache.commons.lang.time.StopWatch.start()V: Line 99
   * Goal 22. org.apache.commons.lang.time.StopWatch.start()V: Line 102
   * Goal 23. org.apache.commons.lang.time.StopWatch.start()V: Line 103
   * Goal 24. org.apache.commons.lang.time.StopWatch.start()V: Line 104
   * Goal 25. org.apache.commons.lang.time.StopWatch.start()V: Line 105
   * Goal 26. org.apache.commons.lang.time.StopWatch.stop()V: Line 115
   * Goal 27. org.apache.commons.lang.time.StopWatch.stop()V: Line 118
   * Goal 28. org.apache.commons.lang.time.StopWatch.stop()V: Line 119
   * Goal 29. org.apache.commons.lang.time.StopWatch.stop()V: Line 120
   * Goal 30. [METHOD] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 31. [METHOD] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 32. [METHOD] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 33. [METHOD] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 34. [METHODNOEX] org.apache.commons.lang.time.StopWatch.<init>()V
   * Goal 35. [METHODNOEX] org.apache.commons.lang.time.StopWatch.getTime()J
   * Goal 36. [METHODNOEX] org.apache.commons.lang.time.StopWatch.start()V
   * Goal 37. [METHODNOEX] org.apache.commons.lang.time.StopWatch.stop()V
   * Goal 38. Weak Mutation 0: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp Negation
   * Goal 39. Weak Mutation 1: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp +1
   * Goal 40. Weak Mutation 2: org.apache.commons.lang.time.StopWatch.start()V:96 - InsertUnaryOp -1
   * Goal 41. Weak Mutation 3: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 0
   * Goal 42. Weak Mutation 4: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 1
   * Goal 43. Weak Mutation 5: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> -1
   * Goal 44. Weak Mutation 6: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceConstant - 2 -> 3
   * Goal 45. Weak Mutation 9: org.apache.commons.lang.time.StopWatch.start()V:96 - ReplaceComparisonOperator != -> >
   * Goal 46. Weak Mutation 11: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp Negation
   * Goal 47. Weak Mutation 12: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp +1
   * Goal 48. Weak Mutation 13: org.apache.commons.lang.time.StopWatch.start()V:99 - InsertUnaryOp -1
   * Goal 49. Weak Mutation 14: org.apache.commons.lang.time.StopWatch.start()V:99 - ReplaceComparisonOperator == -> -2
   * Goal 50. Weak Mutation 18: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 0
   * Goal 51. Weak Mutation 19: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> 1
   * Goal 52. Weak Mutation 20: org.apache.commons.lang.time.StopWatch.start()V:102 - ReplaceConstant - -1 -> -2
   * Goal 53. Weak Mutation 21: org.apache.commons.lang.time.StopWatch.start()V:104 - ReplaceConstant - 1 -> 0
   * Goal 54. Weak Mutation 22: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp Negation
   * Goal 55. Weak Mutation 23: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp +1
   * Goal 56. Weak Mutation 24: org.apache.commons.lang.time.StopWatch.stop()V:115 - InsertUnaryOp -1
   * Goal 57. Weak Mutation 25: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceConstant - 1 -> 0
   * Goal 58. Weak Mutation 26: org.apache.commons.lang.time.StopWatch.stop()V:115 - ReplaceComparisonOperator == -> !=
   * Goal 59. Weak Mutation 39: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 0
   * Goal 60. Weak Mutation 40: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 1
   * Goal 61. Weak Mutation 41: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> -1
   * Goal 62. Weak Mutation 42: org.apache.commons.lang.time.StopWatch.stop()V:119 - ReplaceConstant - 2 -> 3
   * Goal 63. Weak Mutation 123: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp Negation
   * Goal 64. Weak Mutation 124: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp +1
   * Goal 65. Weak Mutation 125: org.apache.commons.lang.time.StopWatch.getTime()J:209 - InsertUnaryOp -1
   * Goal 66. Weak Mutation 126: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 0
   * Goal 67. Weak Mutation 127: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 1
   * Goal 68. Weak Mutation 128: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> -1
   * Goal 69. Weak Mutation 129: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceConstant - 2 -> 3
   * Goal 70. Weak Mutation 130: org.apache.commons.lang.time.StopWatch.getTime()J:209 - ReplaceComparisonOperator == -> -2
   * Goal 71. Weak Mutation 144: org.apache.commons.lang.time.StopWatch.getTime()J:210 - InsertUnaryOp Negation
   * Goal 72. Weak Mutation 145: org.apache.commons.lang.time.StopWatch.getTime()J:210 - InsertUnaryOp Negation
   * Goal 73. Weak Mutation 146: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> +
   * Goal 74. Weak Mutation 147: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> %
   * Goal 75. Weak Mutation 148: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> *
   * Goal 76. Weak Mutation 149: org.apache.commons.lang.time.StopWatch.getTime()J:210 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      StopWatch stopWatch0 = new StopWatch();
      stopWatch0.start();
      System.setCurrentTimeMillis((-691L));
      stopWatch0.stop();
      long long0 = stopWatch0.getTime();
      assertEquals((-1392409282011L), long0);
  }
}
