/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 09:11:25 GMT 2023
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.ArrayUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArrayUtils_ESTest extends ArrayUtils_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 8 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 7 IFNONNULL L320 - false
   * Goal 2. Branch org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 7 IFNONNULL L320 - false in context: org.apache.commons.lang3.ArrayUtils:clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 3. [Output]: org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;:Null
   * Goal 4. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: Line 320
   * Goal 5. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: Line 321
   * Goal 6. [METHOD] org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 7. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 8. Weak Mutation 56: org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;:320 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer[] integerArray0 = ArrayUtils.clone((Integer[]) null);
      assertNull(integerArray0);
  }

  //Test case number: 1
  /*
   * 8 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 7 IFNONNULL L320 - true
   * Goal 2. Branch org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 7 IFNONNULL L320 - true in context: org.apache.commons.lang3.ArrayUtils:clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 3. [Output]: org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;:NonEmptyArray
   * Goal 4. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: Line 320
   * Goal 5. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: Line 323
   * Goal 6. [METHOD] org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 7. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 8. Weak Mutation 56: org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;:320 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Float[] floatArray0 = new Float[2];
      Float[] floatArray1 = ArrayUtils.clone(floatArray0);
      assertFalse(floatArray1.equals((Object)floatArray0));
  }

  //Test case number: 2
  /*
   * 10 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 7 IFNONNULL L320 - true
   * Goal 2. Branch org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: I3 Branch 7 IFNONNULL L320 - true in context: org.apache.commons.lang3.ArrayUtils:clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 3. [Output]: org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;:EmptyArray
   * Goal 4. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: Line 320
   * Goal 5. org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;: Line 323
   * Goal 6. [METHOD] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 7. [METHOD] org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 8. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 9. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;
   * Goal 10. Weak Mutation 56: org.apache.commons.lang3.ArrayUtils.clone([Ljava/lang/Object;)[Ljava/lang/Object;:320 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayUtils arrayUtils0 = new ArrayUtils();
      Object[] objectArray0 = ArrayUtils.clone((Object[]) arrayUtils0.EMPTY_DOUBLE_OBJECT_ARRAY);
      assertEquals(0, objectArray0.length);
  }
}
