/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 09:11:47 GMT 2023
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.StringEscapeUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringEscapeUtils_ESTest extends StringEscapeUtils_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang3.StringEscapeUtils.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang3.StringEscapeUtils.<init>()V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringEscapeUtils stringEscapeUtils0 = new StringEscapeUtils();
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang3.StringEscapeUtils.CsvUnescaper.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang3.StringEscapeUtils.CsvUnescaper.<init>()V
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringEscapeUtils.CsvUnescaper stringEscapeUtils_CsvUnescaper0 = new StringEscapeUtils.CsvUnescaper();
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang3.StringEscapeUtils.CsvEscaper.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang3.StringEscapeUtils.CsvEscaper.<init>()V
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringEscapeUtils.CsvEscaper stringEscapeUtils_CsvEscaper0 = new StringEscapeUtils.CsvEscaper();
  }

  //Test case number: 3
  /*
   * 17 covered goals:
   * Goal 1. org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.StringEscapeUtils:escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:EmptyString
   * Goal 4. org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: Line 556
   * Goal 5. [METHOD] org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 7. Weak Mutation 110: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_XML
   * Goal 8. Weak Mutation 111: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_HTML4
   * Goal 9. Weak Mutation 112: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_ECMASCRIPT
   * Goal 10. Weak Mutation 113: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_CSV
   * Goal 11. Weak Mutation 114: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_XML
   * Goal 12. Weak Mutation 115: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_HTML3
   * Goal 13. Weak Mutation 116: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_ECMASCRIPT
   * Goal 14. Weak Mutation 117: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_JAVA
   * Goal 15. Weak Mutation 118: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_HTML3
   * Goal 16. Weak Mutation 119: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_HTML4
   * Goal 17. Weak Mutation 120: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_JAVA
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = StringEscapeUtils.escapeCsv("");
      assertEquals("", string0);
  }

  //Test case number: 4
  /*
   * 32 covered goals:
   * Goal 1. org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.StringEscapeUtils:escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:NonEmptyString
   * Goal 4. org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: Line 556
   * Goal 5. [METHOD] org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 7. Weak Mutation 132: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:156 - InsertUnaryOp Negation of index
   * Goal 8. Weak Mutation 133: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:156 - InsertUnaryOp IINC 1 index
   * Goal 9. Weak Mutation 134: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:156 - InsertUnaryOp IINC -1 index
   * Goal 10. Weak Mutation 135: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:156 - ReplaceComparisonOperator == -> -2
   * Goal 11. Weak Mutation 139: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:160 - ReplaceComparisonOperator == -> !=
   * Goal 12. Weak Mutation 140: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:163 - ReplaceConstant - 34 -> 0
   * Goal 13. Weak Mutation 141: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:163 - ReplaceConstant - 34 -> 1
   * Goal 14. Weak Mutation 142: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:163 - ReplaceConstant - 34 -> -1
   * Goal 15. Weak Mutation 143: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:163 - ReplaceConstant - 34 -> 33
   * Goal 16. Weak Mutation 144: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:163 - ReplaceConstant - 34 -> 35
   * Goal 17. Weak Mutation 145: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:165 - ReplaceConstant - 34 -> 0
   * Goal 18. Weak Mutation 146: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:165 - ReplaceConstant - 34 -> 1
   * Goal 19. Weak Mutation 147: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:165 - ReplaceConstant - 34 -> -1
   * Goal 20. Weak Mutation 148: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:165 - ReplaceConstant - 34 -> 33
   * Goal 21. Weak Mutation 149: org.apache.commons.lang3.StringEscapeUtils$CsvEscaper.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:165 - ReplaceConstant - 34 -> 35
   * Goal 22. Weak Mutation 110: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_XML
   * Goal 23. Weak Mutation 111: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_HTML4
   * Goal 24. Weak Mutation 112: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_ECMASCRIPT
   * Goal 25. Weak Mutation 113: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_CSV
   * Goal 26. Weak Mutation 114: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_XML
   * Goal 27. Weak Mutation 115: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_HTML3
   * Goal 28. Weak Mutation 116: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_ECMASCRIPT
   * Goal 29. Weak Mutation 117: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_JAVA
   * Goal 30. Weak Mutation 118: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_HTML3
   * Goal 31. Weak Mutation 119: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_HTML4
   * Goal 32. Weak Mutation 120: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_JAVA
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String string0 = StringEscapeUtils.escapeCsv(",");
      assertEquals("\",\"", string0);
  }

  //Test case number: 5
  /*
   * 17 covered goals:
   * Goal 1. org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: root-Branch in context: org.apache.commons.lang3.StringEscapeUtils:escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 3. [Output]: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:Null
   * Goal 4. org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;: Line 556
   * Goal 5. [METHOD] org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;
   * Goal 7. Weak Mutation 110: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_XML
   * Goal 8. Weak Mutation 111: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_HTML4
   * Goal 9. Weak Mutation 112: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_ECMASCRIPT
   * Goal 10. Weak Mutation 113: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_CSV
   * Goal 11. Weak Mutation 114: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_XML
   * Goal 12. Weak Mutation 115: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_HTML3
   * Goal 13. Weak Mutation 116: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_ECMASCRIPT
   * Goal 14. Weak Mutation 117: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_JAVA
   * Goal 15. Weak Mutation 118: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_HTML3
   * Goal 16. Weak Mutation 119: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> ESCAPE_HTML4
   * Goal 17. Weak Mutation 120: org.apache.commons.lang3.StringEscapeUtils.escapeCsv(Ljava/lang/String;)Ljava/lang/String;:556 - ReplaceVariable ESCAPE_CSV -> UNESCAPE_JAVA
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String string0 = StringEscapeUtils.escapeCsv((String) null);
      assertNull(string0);
  }
}
