/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 12:22:43 GMT 2023
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.ArrayUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArrayUtils_ESTest extends ArrayUtils_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 27 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - true
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false
   * Goal 8. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - true
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 10. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I:Negative
   * Goal 11. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: Line 1627
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1659
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 19. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 20. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 21. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 1628: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> >
   * Goal 23. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 24. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 25. Weak Mutation 1669: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> -1
   * Goal 26. Weak Mutation 1670: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> >
   * Goal 27. Weak Mutation 1678: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1659 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object object0 = new Object();
      Object[] objectArray0 = new Object[2];
      int int0 = ArrayUtils.indexOf(objectArray0, object0);
      assertEquals((-1), int0);
  }

  //Test case number: 1
  /*
   * 29 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - false
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 10. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 11. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 12. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 13. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Zero
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1649
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 19. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 20. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1659
   * Goal 21. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1660
   * Goal 22. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 23. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 24. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 25. Weak Mutation 1626: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> -1
   * Goal 26. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 27. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 28. Weak Mutation 1669: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> -1
   * Goal 29. Weak Mutation 1678: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1659 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      Object object0 = new Object();
      objectArray0[0] = object0;
      int int0 = ArrayUtils.indexOf(objectArray0, object0, (-1));
      assertEquals(0, int0);
  }

  //Test case number: 2
  /*
   * 13 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - false
   * Goal 3. org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z: I6 Branch 207 IF_ICMPEQ L1730 - true
   * Goal 4. Branch org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z: I6 Branch 207 IF_ICMPEQ L1730 - true in context: org.apache.commons.lang3.ArrayUtils:contains([Ljava/lang/Object;Ljava/lang/Object;)Z
   * Goal 5. [Output]: org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z:False
   * Goal 6. org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z: Line 1730
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: Line 1627
   * Goal 8. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 9. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1646
   * Goal 10. [METHOD] org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z
   * Goal 11. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z
   * Goal 12. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 13. Weak Mutation 1783: org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z:1730 - ReplaceComparisonOperator == -> -2
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object object0 = new Object();
      boolean boolean0 = ArrayUtils.contains((Object[]) null, object0);
      assertFalse(boolean0);
  }

  //Test case number: 3
  /*
   * 24 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - true
   * Goal 6. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 10. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 11. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 18. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 19. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 20. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 21. Weak Mutation 1627: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> ==
   * Goal 22. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 23. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 24. Weak Mutation 1671: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> ==
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      Object object0 = new Object();
      int int0 = ArrayUtils.indexOf(objectArray0, object0, 1701);
      assertEquals((-1), int0);
  }

  //Test case number: 4
  /*
   * 28 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - false
   * Goal 8. org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z: I6 Branch 207 IF_ICMPEQ L1730 - false
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z: I6 Branch 207 IF_ICMPEQ L1730 - false in context: org.apache.commons.lang3.ArrayUtils:contains([Ljava/lang/Object;Ljava/lang/Object;)Z
   * Goal 10. [Output]: org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z:True
   * Goal 11. org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z: Line 1730
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: Line 1627
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1659
   * Goal 19. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1660
   * Goal 20. [METHOD] org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z
   * Goal 21. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z
   * Goal 22. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 23. Weak Mutation 1628: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> >
   * Goal 24. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 25. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 26. Weak Mutation 1669: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> -1
   * Goal 27. Weak Mutation 1678: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1659 - ReplaceComparisonOperator == -> !=
   * Goal 28. Weak Mutation 1784: org.apache.commons.lang3.ArrayUtils.contains([Ljava/lang/Object;Ljava/lang/Object;)Z:1730 - ReplaceComparisonOperator == -> >=
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Object object0 = new Object();
      Object[] objectArray0 = new Object[2];
      objectArray0[0] = object0;
      boolean boolean0 = ArrayUtils.contains(objectArray0, object0);
      assertTrue(boolean0);
  }

  //Test case number: 5
  /*
   * 22 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - true
   * Goal 5. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 6. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 10. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 11. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 15. [METHOD] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 16. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 17. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 18. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 19. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 1627: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> ==
   * Goal 21. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayUtils arrayUtils0 = new ArrayUtils();
      int int0 = ArrayUtils.indexOf((Object[]) arrayUtils0.EMPTY_CHARACTER_OBJECT_ARRAY, (Object) arrayUtils0, 352);
      assertEquals((-1), int0);
  }

  //Test case number: 6
  /*
   * 22 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - true
   * Goal 5. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 6. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 10. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 11. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1652
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 15. [METHOD] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 16. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 17. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 18. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 19. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 1627: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> ==
   * Goal 21. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 1643: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1652 - ReplaceComparisonOperator >= -> ==
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArrayUtils arrayUtils0 = new ArrayUtils();
      int int0 = ArrayUtils.indexOf(arrayUtils0.EMPTY_OBJECT_ARRAY, (Object) null, 1345);
      assertEquals((-1), int0);
  }

  //Test case number: 7
  /*
   * 25 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - false
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I34 Branch 194 IFNONNULL L1653 - false
   * Goal 6. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 10. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I34 Branch 194 IFNONNULL L1653 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 11. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Zero
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1649
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1652
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1653
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1654
   * Goal 19. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 20. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 21. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 1626: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> -1
   * Goal 23. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 24. Weak Mutation 1641: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1652 - ReplaceComparisonOperator >= -> -1
   * Goal 25. Weak Mutation 1650: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1653 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      int int0 = ArrayUtils.indexOf(objectArray0, (Object) null, (-1));
      assertEquals(0, int0);
  }

  //Test case number: 8
  /*
   * 23 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I34 Branch 194 IFNONNULL L1653 - true
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I34 Branch 194 IFNONNULL L1653 - false
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 9. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I:Positive
   * Goal 10. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: Line 1627
   * Goal 11. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1652
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1653
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1654
   * Goal 17. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 18. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 19. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 1628: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> >
   * Goal 21. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 1641: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1652 - ReplaceComparisonOperator >= -> -1
   * Goal 23. Weak Mutation 1650: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1653 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Object[] objectArray0 = new Object[9];
      objectArray0[0] = (Object) "%+utEA";
      int int0 = ArrayUtils.indexOf(objectArray0, objectArray0[2]);
      assertEquals(1, int0);
  }

  //Test case number: 9
  /*
   * 8 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - false
   * Goal 2. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 3. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1646
   * Goal 6. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 7. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = ArrayUtils.indexOf((Object[]) null, (Object) "%+utEA", (-3553));
      assertEquals((-1), int0);
  }

  //Test case number: 10
  /*
   * 32 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - true
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - true
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 10. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 11. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 12. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 13. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 14. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 15. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1649
   * Goal 19. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 20. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 21. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 22. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1659
   * Goal 23. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 24. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 25. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 26. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 27. Weak Mutation 1626: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> -1
   * Goal 28. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 29. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 30. Weak Mutation 1669: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> -1
   * Goal 31. Weak Mutation 1670: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> >
   * Goal 32. Weak Mutation 1678: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1659 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      Object object0 = new Object();
      int int0 = ArrayUtils.indexOf(objectArray0, object0, (-1));
      assertEquals((-1), int0);
  }

  //Test case number: 11
  /*
   * 22 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - true
   * Goal 5. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 6. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 10. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 11. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1652
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 15. [METHOD] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 16. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 17. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.<init>()V
   * Goal 18. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 19. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 20. Weak Mutation 1628: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> >
   * Goal 21. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 22. Weak Mutation 1642: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1652 - ReplaceComparisonOperator >= -> >
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ArrayUtils arrayUtils0 = new ArrayUtils();
      int int0 = ArrayUtils.indexOf(arrayUtils0.EMPTY_OBJECT_ARRAY, (Object) null, 0);
      assertEquals((-1), int0);
  }

  //Test case number: 12
  /*
   * 31 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - true
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - false
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 10. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 11. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 12. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 13. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 14. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 15. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Positive
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1649
   * Goal 19. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 20. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 21. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 22. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1659
   * Goal 23. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1660
   * Goal 24. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 25. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 26. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 27. Weak Mutation 1626: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> -1
   * Goal 28. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 29. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 30. Weak Mutation 1669: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> -1
   * Goal 31. Weak Mutation 1678: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1659 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      Object object0 = new Object();
      objectArray0[1] = object0;
      int int0 = ArrayUtils.indexOf(objectArray0, object0, (-1));
      assertEquals(1, int0);
  }

  //Test case number: 13
  /*
   * 28 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - true
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I34 Branch 194 IFNONNULL L1653 - true
   * Goal 7. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 9. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 10. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 11. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I28 Branch 193 IF_ICMPGE L1652 - false in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 12. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I34 Branch 194 IFNONNULL L1653 - true in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 13. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:Negative
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1649
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 18. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1652
   * Goal 19. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1653
   * Goal 20. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1664
   * Goal 21. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 22. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I
   * Goal 23. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 24. Weak Mutation 1626: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> -1
   * Goal 25. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 26. Weak Mutation 1641: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1652 - ReplaceComparisonOperator >= -> -1
   * Goal 27. Weak Mutation 1642: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1652 - ReplaceComparisonOperator >= -> >
   * Goal 28. Weak Mutation 1650: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1653 - ReplaceComparisonOperator != null -> = null
   */

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object object0 = new Object();
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = object0;
      objectArray0[1] = object0;
      objectArray0[2] = object0;
      objectArray0[3] = object0;
      objectArray0[4] = object0;
      objectArray0[5] = object0;
      objectArray0[6] = objectArray0[3];
      int int0 = ArrayUtils.indexOf(objectArray0, (Object) null, (-1));
      assertEquals((-1), int0);
  }

  //Test case number: 14
  /*
   * 25 covered goals:
   * Goal 1. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch
   * Goal 2. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I3 Branch 190 IFNONNULL L1645 - true
   * Goal 3. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I11 Branch 191 IFGE L1648 - true
   * Goal 4. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I19 Branch 192 IFNONNULL L1651 - true
   * Goal 5. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I52 Branch 195 IFEQ L1657 - false
   * Goal 6. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I61 Branch 196 IF_ICMPGE L1658 - false
   * Goal 7. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: I69 Branch 197 IFEQ L1659 - false
   * Goal 8. Branch org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: root-Branch in context: org.apache.commons.lang3.ArrayUtils:indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 9. [Output]: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I:Zero
   * Goal 10. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I: Line 1627
   * Goal 11. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1645
   * Goal 12. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1648
   * Goal 13. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1651
   * Goal 14. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1657
   * Goal 15. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1658
   * Goal 16. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1659
   * Goal 17. org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I: Line 1660
   * Goal 18. [METHOD] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 19. [METHODNOEX] org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;)I
   * Goal 20. Weak Mutation 1618: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1645 - ReplaceComparisonOperator != null -> = null
   * Goal 21. Weak Mutation 1628: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1648 - ReplaceComparisonOperator >= -> >
   * Goal 22. Weak Mutation 1630: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1651 - ReplaceComparisonOperator != null -> = null
   * Goal 23. Weak Mutation 1658: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1657 - ReplaceComparisonOperator == -> !=
   * Goal 24. Weak Mutation 1669: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1658 - ReplaceComparisonOperator >= -> -1
   * Goal 25. Weak Mutation 1678: org.apache.commons.lang3.ArrayUtils.indexOf([Ljava/lang/Object;Ljava/lang/Object;I)I:1659 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      Object object0 = new Object();
      objectArray0[0] = object0;
      int int0 = ArrayUtils.indexOf(objectArray0, object0);
      assertEquals(0, int0);
  }
}
