/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 14:26:33 GMT 2023
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.StringUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringUtils_ESTest extends StringUtils_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 8 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true
   * Goal 2. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - true
   * Goal 3. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true
   * Goal 4. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true
   * Goal 5. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false
   * Goal 6. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - false
   * Goal 7. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false
   * Goal 8. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringUtils.contains("The String must not be empty", "The String must not be empty");
      StringUtils.containsIgnoreCase("z~E1h,w", "The String must not be empty");
      StringUtils.contains((String) null, "z~E1h,w");
      StringUtils.containsIgnoreCase("The String must not be empty", (String) null);
  }

  //Test case number: 1
  /*
   * 37 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1015
   * Goal 2. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1018
   * Goal 3. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1045
   * Goal 4. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1046
   * Goal 5. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1048
   * Goal 6. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - true
   * Goal 7. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true
   * Goal 8. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true
   * Goal 9. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true
   * Goal 10. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false
   * Goal 11. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - false
   * Goal 12. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false
   * Goal 13. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false
   * Goal 14. Weak Mutation 500: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator = null -> != null
   * Goal 15. Weak Mutation 503: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator != null -> = null
   * Goal 16. Weak Mutation 509: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> -2
   * Goal 17. Weak Mutation 511: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> <=
   * Goal 18. Weak Mutation 516: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator = null -> != null
   * Goal 19. Weak Mutation 519: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator != null -> = null
   * Goal 20. [Output]: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:True
   * Goal 21. [Output]: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:False
   * Goal 22. [Output]: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:True
   * Goal 23. [Output]: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:False
   * Goal 24. [METHOD] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 25. [METHOD] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 26. [METHOD] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 27. [METHODNOEX] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 28. [METHODNOEX] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 29. [METHODNOEX] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 30. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - true in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 31. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 32. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 33. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - false in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 34. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 35. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 36. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 37. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringUtils.contains("KCl,&]`3s+Wl(2LfDD", "7@iQL8Y.))'Sp@d0O");
      StringUtils.containsIgnoreCase("7@iQL8Y.))'Sp@d0O", "org.apache.commons.lang.ArrayUtils");
      StringUtils stringUtils0 = new StringUtils();
      StringUtils.containsIgnoreCase("l>l!Iw!uf3", "PetJE;52~N74A");
      String string0 = "\\u00";
      StringUtils.containsIgnoreCase("KCl,&]`3s+Wl(2LfDD", (String) null);
      StringUtils.containsIgnoreCase((String) null, "jD_ %Y5]_+=!|1?1o=!");
      StringUtils.containsIgnoreCase((String) null, (String) null);
      StringUtils.containsIgnoreCase("%+utEA", "");
      StringUtils.containsIgnoreCase("", "");
      StringUtils.containsIgnoreCase("", string0);
      StringUtils.contains("", "");
      StringUtils.containsIgnoreCase("org.apache.commons.lang.ArrayUtils", "KCl,&]`3s+Wl(2LfDD");
      StringUtils.containsIgnoreCase("0B!Ve~k&\u0006E|(,N*7L(", "Tp2]]#J/&c<l'TI");
  }

  //Test case number: 2
  /*
   * 34 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1015
   * Goal 2. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1016
   * Goal 3. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1018
   * Goal 4. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1045
   * Goal 5. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1046
   * Goal 6. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1048
   * Goal 7. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true
   * Goal 8. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - true
   * Goal 9. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true
   * Goal 10. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true
   * Goal 11. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false
   * Goal 12. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - false
   * Goal 13. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false
   * Goal 14. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false
   * Goal 15. Weak Mutation 500: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator = null -> != null
   * Goal 16. Weak Mutation 503: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator != null -> = null
   * Goal 17. Weak Mutation 509: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> -2
   * Goal 18. Weak Mutation 511: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> <=
   * Goal 19. Weak Mutation 516: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator = null -> != null
   * Goal 20. Weak Mutation 519: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator != null -> = null
   * Goal 21. [METHOD] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 22. [METHOD] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 23. [METHOD] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 24. [METHODNOEX] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 25. [METHODNOEX] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 26. [METHODNOEX] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 27. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 28. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 29. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - false in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 30. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 31. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 32. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 33. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 34. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringUtils.containsIgnoreCase("DiCjR.d5W@tY3l%", "DiCjR.d5W@tY3l%");
      StringUtils.contains("DiCjR.d5W@tY3l%", "The Character must not be null");
      StringUtils.contains("org.apache.commons.lang.CharUtils", "org.apache.commons.lang.CharUtils");
      StringUtils.contains("DiCjR.d5W@tY3l%", "[k&G1");
      StringUtils.contains((String) null, " is not in the range '0' - '9'");
      StringUtils stringUtils0 = new StringUtils();
      StringUtils.containsIgnoreCase(" ", "");
      StringUtils.containsIgnoreCase("org.apache.commons.lang.CharUtils", " is not in the range '0' - '9'");
      StringUtils.containsIgnoreCase("", "1gA^72uI,#*cn9#!");
      StringUtils.containsIgnoreCase("DiCjR.d5W@tY3l%", "");
      StringUtils.containsIgnoreCase("YP", (String) null);
      StringUtils.contains("", "DiCjR.d5W@tY3l%");
      StringUtils.containsIgnoreCase("kh,W;r BCfm%={'?D", "1gA^72uI,#*cn9#!");
      StringUtils.containsIgnoreCase("", "");
  }

  //Test case number: 3
  /*
   * 31 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1015
   * Goal 2. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1016
   * Goal 3. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1018
   * Goal 4. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1045
   * Goal 5. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1048
   * Goal 6. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true
   * Goal 7. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true
   * Goal 8. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true
   * Goal 9. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false
   * Goal 10. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false
   * Goal 11. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - false
   * Goal 12. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false
   * Goal 13. Weak Mutation 500: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator = null -> != null
   * Goal 14. Weak Mutation 503: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator != null -> = null
   * Goal 15. Weak Mutation 509: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> -2
   * Goal 16. Weak Mutation 511: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> <=
   * Goal 17. Weak Mutation 516: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator = null -> != null
   * Goal 18. Weak Mutation 519: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator != null -> = null
   * Goal 19. [METHOD] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 20. [METHOD] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 21. [METHOD] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 22. [METHODNOEX] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 23. [METHODNOEX] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 24. [METHODNOEX] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 25. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 26. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 27. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 28. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 29. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 30. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 31. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StringUtils.containsIgnoreCase("re5PN]!n`FI7(2C", "re5PN]!n`FI7(2C");
      StringUtils stringUtils0 = new StringUtils();
      StringUtils.containsIgnoreCase("", "re5PN]!n`FI7(2C");
      StringUtils.containsIgnoreCase("T7ZRu", "");
      StringUtils.containsIgnoreCase("re5PN]!n`FI7(2C", "Lb`Qc");
      StringUtils.containsIgnoreCase("", "T7ZRu");
      StringUtils.containsIgnoreCase("", "");
      StringUtils.containsIgnoreCase("re5PN]!n`FI7(2C", "1m6QH+Mf8+OBSP");
      StringUtils.containsIgnoreCase("Lb`Qc", "T7ZRu");
      StringUtils.contains("", "");
      StringUtils.contains("", "re5PN]!n`FI7(2C");
      StringUtils.contains("", (String) null);
      StringUtils.contains("By]^5i(VP?+P3d\"F~", (String) null);
  }

  //Test case number: 4
  /*
   * 31 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1015
   * Goal 2. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: Line 1018
   * Goal 3. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1045
   * Goal 4. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: Line 1048
   * Goal 5. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true
   * Goal 6. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true
   * Goal 7. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - true
   * Goal 8. org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false
   * Goal 9. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false
   * Goal 10. org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false
   * Goal 11. Weak Mutation 500: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator = null -> != null
   * Goal 12. Weak Mutation 503: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1015 - ReplaceComparisonOperator != null -> = null
   * Goal 13. Weak Mutation 509: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> -2
   * Goal 14. Weak Mutation 510: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> !=
   * Goal 15. Weak Mutation 511: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:1018 - ReplaceComparisonOperator < -> <=
   * Goal 16. Weak Mutation 516: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator = null -> != null
   * Goal 17. Weak Mutation 519: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:1045 - ReplaceComparisonOperator != null -> = null
   * Goal 18. [Output]: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:True
   * Goal 19. [Output]: org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z:False
   * Goal 20. [Output]: org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z:True
   * Goal 21. [METHOD] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 22. [METHOD] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 23. [METHOD] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 24. [METHODNOEX] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 25. [METHODNOEX] org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 26. [METHODNOEX] org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 27. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 64 IFNULL L1045 - false in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 28. Branch org.apache.commons.lang.StringUtils.containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 65 IFNONNULL L1045 - true in context: org.apache.commons.lang.StringUtils:containsIgnoreCase(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 29. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I3 Branch 61 IFNULL L1015 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 30. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I5 Branch 62 IFNONNULL L1015 - true in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   * Goal 31. Branch org.apache.commons.lang.StringUtils.contains(Ljava/lang/String;Ljava/lang/String;)Z: I15 Branch 63 IFLT L1018 - false in context: org.apache.commons.lang.StringUtils:contains(Ljava/lang/String;Ljava/lang/String;)Z
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StringUtils.containsIgnoreCase("Minimum abbreviation width is 4", "The Character must not be null");
      StringUtils.containsIgnoreCase("Minimum abbreviation width is 4", "The Character must not be null");
      StringUtils stringUtils0 = new StringUtils();
      StringUtils.containsIgnoreCase("Mdyo/h#|9qdNwX{cZ", "Minimum abbreviation width is 4");
      StringUtils.containsIgnoreCase("b", "The Character must not be null");
      StringUtils.containsIgnoreCase("Minimum abbreviation width is 4", "-nd%Pg");
      StringUtils.containsIgnoreCase("Minimum abbreviation width is 4", "b");
      StringUtils.containsIgnoreCase("", "");
      StringUtils.containsIgnoreCase("Minimum abbreviation width is 4", "");
      StringUtils.containsIgnoreCase("The Character must not be null", "|Yg<!;2^S?*Nz");
      StringUtils.contains("K]E", "");
      StringUtils.containsIgnoreCase("The Character must not be null", "Mdyo/h#|9qdNwX{cZ");
  }
}
