/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 10:44:56 GMT 2023
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.io.Writer;
import org.apache.commons.lang3.text.translate.LookupTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LookupTranslator_ESTest extends LookupTranslator_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 105 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false
   * Goal 2. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true
   * Goal 3. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false
   * Goal 4. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - true
   * Goal 5. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false
   * Goal 6. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true
   * Goal 7. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - false
   * Goal 8. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - true
   * Goal 9. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - true
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - false
   * Goal 11. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I50 Branch 7 IFNULL L73 - true
   * Goal 12. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 13. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 14. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 15. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 16. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 17. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 18. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 19. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 20. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 21. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 22. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I50 Branch 7 IFNULL L73 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 23. [Output]: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:Zero
   * Goal 24. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 25. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 26. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 27. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 28. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 29. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 45
   * Goal 30. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 46
   * Goal 31. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 47
   * Goal 32. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 48
   * Goal 33. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 49
   * Goal 34. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 51
   * Goal 35. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 52
   * Goal 36. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 56
   * Goal 37. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 57
   * Goal 38. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 58
   * Goal 39. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 65
   * Goal 40. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 66
   * Goal 41. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 70
   * Goal 42. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 71
   * Goal 43. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 72
   * Goal 44. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 73
   * Goal 45. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 78
   * Goal 46. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 47. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 48. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 49. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 50. Weak Mutation 0: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp Negation
   * Goal 51. Weak Mutation 1: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp +1
   * Goal 52. Weak Mutation 2: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp -1
   * Goal 53. Weak Mutation 3: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceVariable index -> max
   * Goal 54. Weak Mutation 4: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation of index
   * Goal 55. Weak Mutation 5: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC 1 index
   * Goal 56. Weak Mutation 6: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC -1 index
   * Goal 57. Weak Mutation 7: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation
   * Goal 58. Weak Mutation 8: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp +1
   * Goal 59. Weak Mutation 9: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp -1
   * Goal 60. Weak Mutation 10: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> %
   * Goal 61. Weak Mutation 11: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> -
   * Goal 62. Weak Mutation 12: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> *
   * Goal 63. Weak Mutation 13: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> /
   * Goal 64. Weak Mutation 16: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceComparisonOperator <= -> ==
   * Goal 65. Weak Mutation 25: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable max -> index
   * Goal 66. Weak Mutation 26: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation of max
   * Goal 67. Weak Mutation 27: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC 1 max
   * Goal 68. Weak Mutation 28: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC -1 max
   * Goal 69. Weak Mutation 29: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> max
   * Goal 70. Weak Mutation 30: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> index
   * Goal 71. Weak Mutation 31: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation of i
   * Goal 72. Weak Mutation 32: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC 1 i
   * Goal 73. Weak Mutation 33: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC -1 i
   * Goal 74. Weak Mutation 34: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation
   * Goal 75. Weak Mutation 35: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp +1
   * Goal 76. Weak Mutation 36: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp -1
   * Goal 77. Weak Mutation 37: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> !=
   * Goal 78. Weak Mutation 38: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> -2
   * Goal 79. Weak Mutation 39: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> <=
   * Goal 80. Weak Mutation 70: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> max
   * Goal 81. Weak Mutation 71: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> index
   * Goal 82. Weak Mutation 40: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> max
   * Goal 83. Weak Mutation 41: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> i
   * Goal 84. Weak Mutation 42: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of index
   * Goal 85. Weak Mutation 43: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 index
   * Goal 86. Weak Mutation 44: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 index
   * Goal 87. Weak Mutation 45: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> max
   * Goal 88. Weak Mutation 46: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> i
   * Goal 89. Weak Mutation 47: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of index
   * Goal 90. Weak Mutation 48: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 index
   * Goal 91. Weak Mutation 49: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 index
   * Goal 92. Weak Mutation 50: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable i -> max
   * Goal 93. Weak Mutation 51: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable i -> index
   * Goal 94. Weak Mutation 52: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of i
   * Goal 95. Weak Mutation 53: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 i
   * Goal 96. Weak Mutation 54: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 i
   * Goal 97. Weak Mutation 55: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> %
   * Goal 98. Weak Mutation 56: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> -
   * Goal 99. Weak Mutation 57: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> *
   * Goal 100. Weak Mutation 58: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> /
   * Goal 101. Weak Mutation 59: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:72 - ReplaceVariable subSeq -> input
   * Goal 102. Weak Mutation 60: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceVariable result -> subSeq
   * Goal 103. Weak Mutation 61: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceVariable result -> input
   * Goal 104. Weak Mutation 62: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceComparisonOperator = null -> != null
   * Goal 105. Weak Mutation 72: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:78 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[4][5];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      CharSequence charSequence1 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn(2685, 2685, (-2393), 580, 2859).when(charSequence1).length();
      doReturn(charSequence0, (CharSequence) null, (CharSequence) null, (CharSequence) null, (CharSequence) null).when(charSequence1).subSequence(anyInt() , anyInt());
      charSequenceArray1[0] = charSequence1;
      charSequenceArray0[0] = charSequenceArray1;
      charSequenceArray0[1] = charSequenceArray0[0];
      charSequenceArray0[2] = charSequenceArray0[1];
      charSequenceArray0[3] = charSequenceArray0[1];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter();
      int int0 = lookupTranslator0.translate(charSequence1, (-1), (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  //Test case number: 1
  /*
   * 21 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false
   * Goal 2. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false
   * Goal 3. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false
   * Goal 4. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true
   * Goal 5. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 6. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 7. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 8. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 9. <init>([[Ljava/lang/CharSequence;)V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 11. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 12. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 13. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 14. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 15. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 45
   * Goal 16. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 46
   * Goal 17. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 47
   * Goal 18. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 48
   * Goal 19. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 49
   * Goal 20. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 51
   * Goal 21. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[3][8];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(charSequence0).length();
      charSequenceArray1[0] = charSequence0;
      charSequenceArray0[0] = charSequenceArray1;
      CharSequence[] charSequenceArray2 = new CharSequence[1];
      charSequenceArray0[1] = charSequenceArray2;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  //Test case number: 2
  /*
   * 88 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false
   * Goal 2. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true
   * Goal 3. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false
   * Goal 4. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - true
   * Goal 5. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false
   * Goal 6. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true
   * Goal 7. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - true
   * Goal 8. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - true
   * Goal 9. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - false
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I50 Branch 7 IFNULL L73 - true
   * Goal 11. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 12. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 13. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 14. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 15. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 16. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 17. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 18. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 19. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 20. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I50 Branch 7 IFNULL L73 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 21. [Output]: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:Zero
   * Goal 22. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 23. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 24. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 25. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 26. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 27. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 45
   * Goal 28. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 46
   * Goal 29. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 47
   * Goal 30. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 48
   * Goal 31. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 49
   * Goal 32. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 51
   * Goal 33. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 56
   * Goal 34. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 57
   * Goal 35. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 58
   * Goal 36. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 65
   * Goal 37. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 66
   * Goal 38. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 70
   * Goal 39. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 71
   * Goal 40. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 72
   * Goal 41. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 73
   * Goal 42. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 78
   * Goal 43. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 44. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 45. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 46. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 47. Weak Mutation 0: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp Negation
   * Goal 48. Weak Mutation 1: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp +1
   * Goal 49. Weak Mutation 2: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp -1
   * Goal 50. Weak Mutation 4: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation of index
   * Goal 51. Weak Mutation 5: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC 1 index
   * Goal 52. Weak Mutation 6: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC -1 index
   * Goal 53. Weak Mutation 7: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation
   * Goal 54. Weak Mutation 8: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp +1
   * Goal 55. Weak Mutation 9: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp -1
   * Goal 56. Weak Mutation 10: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> %
   * Goal 57. Weak Mutation 13: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> /
   * Goal 58. Weak Mutation 15: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceComparisonOperator <= -> <
   * Goal 59. Weak Mutation 26: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation of max
   * Goal 60. Weak Mutation 27: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC 1 max
   * Goal 61. Weak Mutation 28: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC -1 max
   * Goal 62. Weak Mutation 29: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> max
   * Goal 63. Weak Mutation 30: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> index
   * Goal 64. Weak Mutation 31: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation of i
   * Goal 65. Weak Mutation 32: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC 1 i
   * Goal 66. Weak Mutation 33: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC -1 i
   * Goal 67. Weak Mutation 34: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation
   * Goal 68. Weak Mutation 35: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp +1
   * Goal 69. Weak Mutation 36: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp -1
   * Goal 70. Weak Mutation 38: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> -2
   * Goal 71. Weak Mutation 39: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> <=
   * Goal 72. Weak Mutation 70: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> max
   * Goal 73. Weak Mutation 71: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> index
   * Goal 74. Weak Mutation 42: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of index
   * Goal 75. Weak Mutation 43: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 index
   * Goal 76. Weak Mutation 44: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 index
   * Goal 77. Weak Mutation 47: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of index
   * Goal 78. Weak Mutation 48: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 index
   * Goal 79. Weak Mutation 49: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 index
   * Goal 80. Weak Mutation 52: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of i
   * Goal 81. Weak Mutation 53: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 i
   * Goal 82. Weak Mutation 54: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 i
   * Goal 83. Weak Mutation 55: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> %
   * Goal 84. Weak Mutation 58: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> /
   * Goal 85. Weak Mutation 59: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:72 - ReplaceVariable subSeq -> input
   * Goal 86. Weak Mutation 61: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceVariable result -> input
   * Goal 87. Weak Mutation 62: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceComparisonOperator = null -> != null
   * Goal 88. Weak Mutation 72: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:78 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[2][0];
      CharSequence[] charSequenceArray1 = new CharSequence[2];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0, 0).when(charSequence0).length();
      doReturn((CharSequence) null).when(charSequence0).subSequence(anyInt() , anyInt());
      charSequenceArray1[0] = charSequence0;
      charSequenceArray0[0] = charSequenceArray1;
      charSequenceArray0[1] = charSequenceArray0[0];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter(0);
      int int0 = lookupTranslator0.translate(charSequence0, 0, (Writer) stringWriter0);
      assertEquals(0, int0);
  }

  //Test case number: 3
  /*
   * 30 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false
   * Goal 2. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true
   * Goal 3. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 4. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 5. translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I_java.lang.NullPointerException_IMPLICIT
   * Goal 6. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 7. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 8. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 9. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 11. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 45
   * Goal 12. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 56
   * Goal 13. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 57
   * Goal 14. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 58
   * Goal 15. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 65
   * Goal 16. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 66
   * Goal 17. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 18. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 19. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 20. Weak Mutation 0: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp Negation
   * Goal 21. Weak Mutation 1: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp +1
   * Goal 22. Weak Mutation 2: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp -1
   * Goal 23. Weak Mutation 4: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation of index
   * Goal 24. Weak Mutation 5: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC 1 index
   * Goal 25. Weak Mutation 6: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC -1 index
   * Goal 26. Weak Mutation 7: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation
   * Goal 27. Weak Mutation 8: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp +1
   * Goal 28. Weak Mutation 9: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp -1
   * Goal 29. Weak Mutation 10: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> %
   * Goal 30. Weak Mutation 13: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> /
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[0][8];
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter();
      // Undeclared exception!
      try { 
        lookupTranslator0.translate((CharSequence) null, 0, (Writer) stringWriter0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 4
  /*
   * 22 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false
   * Goal 2. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false
   * Goal 3. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false
   * Goal 4. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - false
   * Goal 5. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 6. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 7. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 8. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 9. <init>([[Ljava/lang/CharSequence;)V_java.lang.NullPointerException_IMPLICIT
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 11. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 12. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 13. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 14. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 15. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 45
   * Goal 16. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 46
   * Goal 17. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 47
   * Goal 18. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 48
   * Goal 19. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 49
   * Goal 20. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 51
   * Goal 21. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 52
   * Goal 22. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[4][7];
      CharSequence[] charSequenceArray1 = new CharSequence[5];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn(1635).when(charSequence0).length();
      charSequenceArray1[0] = charSequence0;
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = null;
      try {
        lookupTranslator0 = new LookupTranslator(charSequenceArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.lang3.text.translate.LookupTranslator", e);
      }
  }

  //Test case number: 5
  /*
   * 12 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - true
   * Goal 2. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 3. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 4. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 5. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 6. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 7. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 8. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 56
   * Goal 9. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 57
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 58
   * Goal 11. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 12. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LookupTranslator lookupTranslator0 = new LookupTranslator((CharSequence[][]) null);
  }

  //Test case number: 6
  /*
   * 110 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false
   * Goal 2. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true
   * Goal 3. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false
   * Goal 4. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false
   * Goal 5. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true
   * Goal 6. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - true
   * Goal 7. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - false
   * Goal 8. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - true
   * Goal 9. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - false
   * Goal 10. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I50 Branch 7 IFNULL L73 - true
   * Goal 11. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I22 Branch 1 IFNULL L44 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 12. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 13. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I37 Branch 2 IF_ICMPGE L45 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 14. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I65 Branch 3 IF_ICMPGE L48 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 15. Branch org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: I74 Branch 4 IF_ICMPLE L51 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:<init>([[Ljava/lang/CharSequence;)V
   * Goal 16. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 17. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I13 Branch 5 IF_ICMPLE L66 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 18. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 19. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I29 Branch 6 IF_ICMPLT L70 - false in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 20. Branch org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: I50 Branch 7 IFNULL L73 - true in context: org.apache.commons.lang3.text.translate.LookupTranslator:translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 21. translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I_org.evosuite.runtime.TooManyResourcesException_IMPLICIT
   * Goal 22. [Output]: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:Zero
   * Goal 23. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 40
   * Goal 24. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 41
   * Goal 25. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 42
   * Goal 26. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 43
   * Goal 27. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 44
   * Goal 28. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 45
   * Goal 29. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 46
   * Goal 30. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 47
   * Goal 31. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 48
   * Goal 32. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 49
   * Goal 33. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 51
   * Goal 34. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 56
   * Goal 35. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 57
   * Goal 36. org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V: Line 58
   * Goal 37. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 65
   * Goal 38. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 66
   * Goal 39. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 67
   * Goal 40. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 70
   * Goal 41. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 71
   * Goal 42. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 72
   * Goal 43. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 73
   * Goal 44. org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I: Line 78
   * Goal 45. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 46. [METHOD] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 47. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.<init>([[Ljava/lang/CharSequence;)V
   * Goal 48. [METHODNOEX] org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I
   * Goal 49. Weak Mutation 0: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp Negation
   * Goal 50. Weak Mutation 1: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp +1
   * Goal 51. Weak Mutation 2: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:65 - InsertUnaryOp -1
   * Goal 52. Weak Mutation 3: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceVariable index -> max
   * Goal 53. Weak Mutation 4: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation of index
   * Goal 54. Weak Mutation 5: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC 1 index
   * Goal 55. Weak Mutation 6: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp IINC -1 index
   * Goal 56. Weak Mutation 7: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp Negation
   * Goal 57. Weak Mutation 8: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp +1
   * Goal 58. Weak Mutation 9: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - InsertUnaryOp -1
   * Goal 59. Weak Mutation 10: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> %
   * Goal 60. Weak Mutation 13: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceArithmeticOperator + -> /
   * Goal 61. Weak Mutation 14: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceComparisonOperator <= -> -1
   * Goal 62. Weak Mutation 16: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:66 - ReplaceComparisonOperator <= -> ==
   * Goal 63. Weak Mutation 17: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - ReplaceVariable index -> max
   * Goal 64. Weak Mutation 18: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - InsertUnaryOp Negation of index
   * Goal 65. Weak Mutation 19: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - InsertUnaryOp IINC 1 index
   * Goal 66. Weak Mutation 20: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - InsertUnaryOp IINC -1 index
   * Goal 67. Weak Mutation 21: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - ReplaceArithmeticOperator - -> +
   * Goal 68. Weak Mutation 22: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - ReplaceArithmeticOperator - -> %
   * Goal 69. Weak Mutation 23: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - ReplaceArithmeticOperator - -> *
   * Goal 70. Weak Mutation 24: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:67 - ReplaceArithmeticOperator - -> /
   * Goal 71. Weak Mutation 25: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable max -> index
   * Goal 72. Weak Mutation 26: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation of max
   * Goal 73. Weak Mutation 27: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC 1 max
   * Goal 74. Weak Mutation 28: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC -1 max
   * Goal 75. Weak Mutation 29: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> max
   * Goal 76. Weak Mutation 30: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> index
   * Goal 77. Weak Mutation 31: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation of i
   * Goal 78. Weak Mutation 32: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC 1 i
   * Goal 79. Weak Mutation 33: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp IINC -1 i
   * Goal 80. Weak Mutation 34: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp Negation
   * Goal 81. Weak Mutation 35: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp +1
   * Goal 82. Weak Mutation 36: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - InsertUnaryOp -1
   * Goal 83. Weak Mutation 37: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> !=
   * Goal 84. Weak Mutation 38: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> -2
   * Goal 85. Weak Mutation 39: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceComparisonOperator < -> <=
   * Goal 86. Weak Mutation 70: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> max
   * Goal 87. Weak Mutation 71: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:70 - ReplaceVariable i -> index
   * Goal 88. Weak Mutation 40: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> max
   * Goal 89. Weak Mutation 41: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> i
   * Goal 90. Weak Mutation 42: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of index
   * Goal 91. Weak Mutation 43: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 index
   * Goal 92. Weak Mutation 44: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 index
   * Goal 93. Weak Mutation 45: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> max
   * Goal 94. Weak Mutation 46: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable index -> i
   * Goal 95. Weak Mutation 47: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of index
   * Goal 96. Weak Mutation 48: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 index
   * Goal 97. Weak Mutation 49: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 index
   * Goal 98. Weak Mutation 50: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable i -> max
   * Goal 99. Weak Mutation 51: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceVariable i -> index
   * Goal 100. Weak Mutation 52: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp Negation of i
   * Goal 101. Weak Mutation 53: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC 1 i
   * Goal 102. Weak Mutation 54: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - InsertUnaryOp IINC -1 i
   * Goal 103. Weak Mutation 55: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> %
   * Goal 104. Weak Mutation 56: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> -
   * Goal 105. Weak Mutation 57: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> *
   * Goal 106. Weak Mutation 58: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:71 - ReplaceArithmeticOperator + -> /
   * Goal 107. Weak Mutation 59: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:72 - ReplaceVariable subSeq -> input
   * Goal 108. Weak Mutation 61: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceVariable result -> input
   * Goal 109. Weak Mutation 62: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:73 - ReplaceComparisonOperator = null -> != null
   * Goal 110. Weak Mutation 72: org.apache.commons.lang3.text.translate.LookupTranslator.translate(Ljava/lang/CharSequence;ILjava/io/Writer;)I:78 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CharSequence[][] charSequenceArray0 = new CharSequence[1][8];
      CharSequence[] charSequenceArray1 = new CharSequence[3];
      CharSequence charSequence0 = mock(CharSequence.class, new ViolatedAssumptionAnswer());
      doReturn((-2071), (-2071), (-2071), (-1346), 2914).when(charSequence0).length();
      doReturn((CharSequence) null, (CharSequence) null, (CharSequence) null, (CharSequence) null, (CharSequence) null).when(charSequence0).subSequence(anyInt() , anyInt());
      charSequenceArray1[0] = charSequence0;
      charSequenceArray0[0] = charSequenceArray1;
      LookupTranslator lookupTranslator0 = new LookupTranslator(charSequenceArray0);
      StringWriter stringWriter0 = new StringWriter(0);
      lookupTranslator0.translate(charSequence0, (-556), (Writer) stringWriter0);
      lookupTranslator0.translate(charSequence0, 0, (Writer) null);
      lookupTranslator0.translate(charSequence0, 1, (Writer) null);
      lookupTranslator0.translate(charSequence0, (-262), (Writer) stringWriter0);
      // Undeclared exception!
      lookupTranslator0.translate(charSequence0, 669, (Writer) null);
  }
}
