/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 11:36:55 GMT 2023
 */

package org.apache.commons.lang3;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.lang3.Validate;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Validate_ESTest extends Validate_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 11 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(Z)V: I3 Branch 4 IFNE L176 - false
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(Z)V: I3 Branch 4 IFNE L176 - false in context: org.apache.commons.lang3.Validate:isTrue(Z)V
   * Goal 3. isTrue(Z)V_java.lang.IllegalArgumentException_EXPLICIT
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(Z)V: Line 176
   * Goal 5. org.apache.commons.lang3.Validate.isTrue(Z)V: Line 177
   * Goal 6. [METHOD] org.apache.commons.lang3.Validate.isTrue(Z)V
   * Goal 7. Weak Mutation 18: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 19: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 20: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 21: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - ReplaceComparisonOperator != -> ==
   * Goal 11. Weak Mutation 22: org.apache.commons.lang3.Validate.isTrue(Z)V:177 - ReplaceConstant - The validated expression is false -> 
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Validate.isTrue(false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The validated expression is false
         //
         verifyException("org.apache.commons.lang3.Validate", e);
      }
  }

  //Test case number: 1
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang3.Validate.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang3.Validate.<init>()V
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Validate validate0 = new Validate();
  }

  //Test case number: 2
  /*
   * 10 covered goals:
   * Goal 1. org.apache.commons.lang3.Validate.isTrue(Z)V: I3 Branch 4 IFNE L176 - true
   * Goal 2. Branch org.apache.commons.lang3.Validate.isTrue(Z)V: I3 Branch 4 IFNE L176 - true in context: org.apache.commons.lang3.Validate:isTrue(Z)V
   * Goal 3. org.apache.commons.lang3.Validate.isTrue(Z)V: Line 176
   * Goal 4. org.apache.commons.lang3.Validate.isTrue(Z)V: Line 179
   * Goal 5. [METHOD] org.apache.commons.lang3.Validate.isTrue(Z)V
   * Goal 6. [METHODNOEX] org.apache.commons.lang3.Validate.isTrue(Z)V
   * Goal 7. Weak Mutation 18: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - InsertUnaryOp Negation of expression
   * Goal 8. Weak Mutation 19: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - InsertUnaryOp IINC 1 expression
   * Goal 9. Weak Mutation 20: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - InsertUnaryOp IINC -1 expression
   * Goal 10. Weak Mutation 21: org.apache.commons.lang3.Validate.isTrue(Z)V:176 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Validate.isTrue(true);
  }
}
