/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 09:12:24 GMT 2023
 */

package org.apache.commons.lang3.text.translate;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang3.text.translate.AggregateTranslator;
import org.apache.commons.lang3.text.translate.CharSequenceTranslator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AggregateTranslator_ESTest extends AggregateTranslator_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 7 covered goals:
   * Goal 1. org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V: root-Branch
   * Goal 2. Branch org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V: root-Branch in context: org.apache.commons.lang3.text.translate.AggregateTranslator:<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V
   * Goal 3. org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V: Line 40
   * Goal 4. org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V: Line 41
   * Goal 5. org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V: Line 42
   * Goal 6. [METHOD] org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V
   * Goal 7. [METHODNOEX] org.apache.commons.lang3.text.translate.AggregateTranslator.<init>([Lorg/apache/commons/lang3/text/translate/CharSequenceTranslator;)V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CharSequenceTranslator[] charSequenceTranslatorArray0 = new CharSequenceTranslator[1];
      AggregateTranslator aggregateTranslator0 = new AggregateTranslator(charSequenceTranslatorArray0);
  }
}
