/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 29 20:34:00 GMT 2023
 */

package org.apache.commons.lang;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.lang.StringUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringUtils_ESTest extends StringUtils_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 10 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I3 Branch 1 IFNULL L185 - false
   * Goal 2. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I6 Branch 2 IFNE L185 - true
   * Goal 3. Branch org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I6 Branch 2 IFNE L185 - true in context: org.apache.commons.lang.StringUtils:isEmpty(Ljava/lang/String;)Z
   * Goal 4. Branch org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I3 Branch 1 IFNULL L185 - false in context: org.apache.commons.lang.StringUtils:isEmpty(Ljava/lang/String;)Z
   * Goal 5. [Output]: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:False
   * Goal 6. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: Line 185
   * Goal 7. [METHOD] org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z
   * Goal 8. [METHODNOEX] org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z
   * Goal 9. Weak Mutation 1: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:185 - ReplaceComparisonOperator = null -> != null
   * Goal 10. Weak Mutation 4: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:185 - ReplaceComparisonOperator != -> <
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = StringUtils.isEmpty("Cannot pad a negative amount: ");
      assertFalse(boolean0);
  }

  //Test case number: 1
  /*
   * 7 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I3 Branch 1 IFNULL L185 - true
   * Goal 2. Branch org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I3 Branch 1 IFNULL L185 - true in context: org.apache.commons.lang.StringUtils:isEmpty(Ljava/lang/String;)Z
   * Goal 3. [Output]: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:True
   * Goal 4. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: Line 185
   * Goal 5. [METHOD] org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z
   * Goal 6. [METHODNOEX] org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z
   * Goal 7. Weak Mutation 1: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:185 - ReplaceComparisonOperator = null -> != null
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = StringUtils.isEmpty((String) null);
      assertTrue(boolean0);
  }

  //Test case number: 2
  /*
   * 10 covered goals:
   * Goal 1. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I3 Branch 1 IFNULL L185 - false
   * Goal 2. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I6 Branch 2 IFNE L185 - false
   * Goal 3. Branch org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I6 Branch 2 IFNE L185 - false in context: org.apache.commons.lang.StringUtils:isEmpty(Ljava/lang/String;)Z
   * Goal 4. Branch org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: I3 Branch 1 IFNULL L185 - false in context: org.apache.commons.lang.StringUtils:isEmpty(Ljava/lang/String;)Z
   * Goal 5. [Output]: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:True
   * Goal 6. org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z: Line 185
   * Goal 7. [METHOD] org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z
   * Goal 8. [METHODNOEX] org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z
   * Goal 9. Weak Mutation 1: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:185 - ReplaceComparisonOperator = null -> != null
   * Goal 10. Weak Mutation 3: org.apache.commons.lang.StringUtils.isEmpty(Ljava/lang/String;)Z:185 - ReplaceComparisonOperator != -> -1
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = StringUtils.isEmpty("");
      assertTrue(boolean0);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * Goal 1. [METHOD] org.apache.commons.lang.StringUtils.<init>()V
   * Goal 2. [METHODNOEX] org.apache.commons.lang.StringUtils.<init>()V
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      assertEquals((-1), StringUtils.INDEX_NOT_FOUND);
  }
}
